# Generated by Django 2.1.5 on 2019-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190209_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='image',
        ),
        migrations.AddField(
            model_name='treasure',
            name='img_url',
            field=models.CharField(default='static/images/gold-nugget.jpeg', max_length=100),
            preserve_default=False,
        ),
    ]
