# Generated by Django 2.1.5 on 2019-02-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_treasure_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='user',
        ),
    ]
